inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6

RSpec/EmptyLineAfterHook:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/HashConversion:
  Exclude:
    - spec/**/*_spec.rb
